my_site/my_site/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'my_site.views.home', name='home'),
    url(r'^polls/', include('polls.urls', namespace="polls")),

    url(r'^admin/', include(admin.site.urls)),
)

my_site/polls/urls.py
from django.conf.urls import patterns , url

from polls import views

urlpatterns = patterns('',
 url(r'^$' , views.IndexView.as_view(), name='index'),
 url(r'^(?P<pk>\d+)/$' , views.DetailView.as_view() , name='detail'),
 url(r'^(?P<pk>\d+)/results/$' , views.ResultsView.as_view() , name='results'),
 url(r'^(?P<question_id>\d+)/vote/$' , views.vote , name='vote'),
 url(r'^register/$', views.register ,name='register'),
 url(r'^login/$', views.user_login , name='login'),
 url(r'^logout/$',views.user_logout, name='logout'),
 )

my_site/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class UserProfile(models.Model):
	user = models.OneToOneField(User)
	picture = models.ImageField(upload_to='profile_images', blank=True)
	def __unicode__(self):
		return self.user.username


class Question(models.Model):
	question=models.CharField(max_length=200)
	pub_date=models.DateTimeField('date published')
	def __unicode__(self):
		return self.question
	def was_published_recently(self):
		now = timezone.now()
		return now >= self.pub_date >= now - datetime.timedelta(days=1)
	was_published_recently.admin_order_field ='-pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'

				

class Choice(models.Model):
	question=models.ForeignKey(Question)
	choice_text=models.CharField(max_length=200)
	votes=models.IntegerField(default=0)
	def __unicode__(self):
		return self.choice_text

	

# Create your models here.

my_site/polls/forms.py
from django import forms
from django.contrib.auth.models import User
from polls.models import UserProfile

class UserForm(forms.ModelForm):
	password = forms.CharField(widget = forms.PasswordInput())

	class Meta:
		model = User
		fields = ('username' , 'email' , 'password')

class UserProfileForm(forms.ModelForm):
	class Meta :
		model = UserProfile
		fields = ('picture',)

my_site/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
import datetime

#from django.template import RequestContext , loader

from polls.models import Question, Choice
from polls.forms import UserForm, UserProfileForm

#class IndexView(generic.ListView):
#	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	#output = ', '.join([p.question for p in latest_question_list])
	#template = loader.get_template('polls/index.html')
#	context = {	'latest_question_list' : latest_question_list }
	#return HttpResponse(template.render(context))
#	return render(request, 'polls/index.html', context)

def register(request):
	registered=False

	if(request.method) == 'POST':
		user_form = UserForm(data=request.POST)
		profile_form=UserProfileForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password) 
			user.save()
			profile = profile_form.save(commit=False)
			profile.user=user

			if 'picture' in request.FILES:
				profile.picture = request.Files[ 'picture']

			profile.save()
			registered = True

		else:
			print user_form.errors, profile_form.errors

	else:
		user_form = UserForm()
		profile_form = UserProfileForm()

	return render(request,'polls/register.html' , 
		{ 'user_form': user_form, 'profile_form':profile_form, 'registered':registered})

def user_login(request):
	if request.method == 'POST': 
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username, password=password)

		if user:
			if user.is_active:
				login(request, user)
				print "abc"
				return HttpResponseRedirect('/polls/')
			else:
				return HttpResponse("Your account is disabled")
		else:
			print "Invalid Login details : {0} , {1} ".format(username, password)
			return HttpResponse(" Invalid login details supplied")
	else:
		return render(request, 'polls/login.html', {})


@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect('/polls/')


class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'


	def get_queryset(self):
		a=[]
		for q in Question.objects.all():
			c=q.choice_set.all()
			if c :
				if q.pub_date<=timezone.now():
					a.append(q)
		#Q=Question.objects.create(question="How are you?", pub_date=timezone.now()-datetime.timedelta(days=2)) 
		#a.append(Q)

		return a

		#return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'
	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now())
#@login_required
class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'

@login_required
def vote(request, question_id):
	p=get_object_or_404(Question,pk=question_id)
	try:
		selected_choice = p.choice_set.get(pk=request.POST['choice'])
	except(KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {
			'question' : p,
			'error_message' : "You did'nt select a choice.",
			})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:results' , args=(p.id,)))

my_site/polls/templates/polls/detail.html
<!--{{ question }}-->


<h1>{{question.question}}</h1>
<!--<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>-->
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action ="{% url 'polls:vote' question.id %}" method="post"> 
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />

	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

my_site/polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if user.is_authenticated %}
	<h2>Welcome to MyPolls App {{ user.username }}</h2>
{% else %}
	<h2>Welcome to MyPolls App</h2>
{% endif %}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <!--<li><a href="/polls/{{ question.id }}/">{{ question.question }}</a></li>-->
        <li>
        <a href="{% url 'polls:detail' question.id %}">{{ question.question}}</a> 
        
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p> No polls are available.</p>
{% endif %}
<br/>
{% if user.is_authenticated %}
	<a href="/polls/logout/">Logout </a>
{% else %}
<a href="/polls/login/">Login </a>
&nbsp
<a href="/polls/register/">Register Here</a>
{% endif %}

my_site/polls/templates/polls/login.html
<h1>Login to MyPolls App</h1>
<form id="login_form" method="post" action="{% url 'polls:login' %}">
{% csrf_token %}
	Username : <input type="text" name="username" value="" size="50" />
	<br />
	Password : <input type="password" name="password" value="" size="50"/>
	<br />

	<input type="submit" value="submit" />

</form>
<br />
<a href="/polls/register/">Do not have an account? Register Here.</a>

my_site/polls/templates/polls/register.html
{% if registered %}
	<strong>Thank You for Registering! </strong>
	<a href="/polls/login/">Login Now</a>
{% else %}
	<strong>Register here!</strong>
<form id="user_form" method="post" action="/polls/register/" enctype="multipart/form-data">
	{% csrf_token %}
		{{user_form.as_p}}
		{{profile_form.as_p}}
	<input type = "submit" name="submit" value="Register" />
</form>
{% endif %}

my_site/polls/templates/polls/results.html
<h1>{{question.question}}</h1>

<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote {{ choice.votes|pluralize }}
	</li>
{% endfor %}
</ul>

<a href ="{% url 'polls:index' %}">Vote again ?</a>

my_site/templates/base_site.html
{% extends "admin/base.html" %}

{% block title %}{{ title }} | {{ site_title|default:_('Django site admin') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Polls Administration</a></h1>
{% endblock %}

{% block nav-global %}{% endblock %}